### ISSUE TITLE
Release failure of resized_image_transort

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#2269]
This causes unreleased ros-kinetic-resized-image-transport and jsk-pcl-ros.

http://build.ros.org/job/Kbin_uX64__resized_image_transport__ubuntu_xenial_amd64__binary/63/console

```
17:43:40 Looking for the '.dsc' file of package 'ros-kinetic-resized-image-transport' with version '1.2.5-0'
17:43:41 Traceback (most recent call last):
17:43:41   File "/usr/lib/python3/dist-packages/apt/cache.py", line 194, in __getitem__
17:43:41     return self._weakref[key]
17:43:41   File "/usr/lib/python3.5/weakref.py", line 131, in __getitem__
17:43:41     o = self.data[key]()
17:43:41 KeyError: 'ros-kinetic-jsk-recognition-utils'
17:43:41 
17:43:41 During handling of the above exception, another exception occurred:
17:43:41 
17:43:41 Traceback (most recent call last):
17:43:41   File "/usr/lib/python3/dist-packages/apt/cache.py", line 198, in __getitem__
17:43:41     rawpkg = self._cache[key]
17:43:41 KeyError: 'ros-kinetic-jsk-recognition-utils'
17:43:41 
17:43:41 During handling of the above exception, another exception occurred:
17:43:41 
17:43:41 Traceback (most recent call last):
17:43:41   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 163, in <module>
17:43:41     main()
17:43:41   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 85, in main
17:43:41     apt_cache, debian_pkg_names)
17:43:41   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 144, in get_binary_package_versions
17:43:41     pkg = apt_cache[debian_pkg_name]
17:43:41   File "/usr/lib/python3/dist-packages/apt/cache.py", line 200, in __getitem__
17:43:41     raise KeyError('The cache has no package named %r' % key)
17:43:41 KeyError: "The cache has no package named 'ros-kinetic-jsk-recognition-utils'"
17:43:45 Build step 'Execute shell' marked build as failure
```

**Comment by k-okada** [comment]
it is ok now => http://build.ros.org/job/Kbin_uX64__resized_image_transport__ubuntu_xenial_amd64__binary/65/
