### ISSUE TITLE
Permission denied when run install_sample_data.py installed from debian

### ISSUE THREAD

**Issue by tongtybj** [jsk-ros-pkg/jsk_recognition#2591]
@knorth55 
If I use `jsk_recognition` installed from apt-get, I counter following permission denied problem. Did I miss something important point?  I don't think `sudo` is a good idea.

```
chou@home-PC:/opt/ros/melodic/share/jsk_perception$ rosrun jsk_perception install_sample_data.py 
Traceback (most recent call last):
  File "/opt/ros/melodic/share/jsk_perception/scripts/install_sample_data.py", line 70, in <module>
    main()
  File "/opt/ros/melodic/share/jsk_perception/scripts/install_sample_data.py", line 16, in main
    'sample/data/2016-11-11-12-53-06_in_lab.bag',
  File "/opt/ros/melodic/lib/python2.7/dist-packages/jsk_data/download_data.py", line 171, in download_data
    os.makedirs(osp.dirname(path))
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/ros/melodic/share/jsk_perception/sample/data'
```

Btw, I find a similar unsolved issue #2424.

**Comment by knorth55** [comment]
is this a problem only for `mkdir` or `ln -sf` after `mkdir`?
If it is just a `mkdir` problem, we can add the directory in this repo and skip making it.
